import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import ThemeRegistry from '@/src/components/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Frontend Mentor | E-commerce product page',
  description: 'Generated by create next app',
  icons: '/icon.png'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <ThemeRegistry>
        <body>{children}</body>
      </ThemeRegistry>
    </html>
  );
}
