export const THEMES = {
  LIGHT: "LIGHT",
  DARK: "DARK",
};

export const FormActionTypes = {
  NEXT: "NEXT",
  PREV: "PREV",
  CONFIRM: "CONFIRM",
  GO_CHANGE_PLAN: "GO_CHANGE_PLAN",
  UPDATE_PERSONAL_INFO: "UPDATE_PERSONAL_INFO",
  VALIDATE_PERSONAL_INTO: "VALIDATE_PERSONAL_INTO",
  IS_VALIDATE_PERSONAL_INTO: "IS_VALIDATE_PERSONAL_INTO",
  CHANGE_PLAN: "CHANGE_PLAN",
  UPDATE_SELECTED_PLAN: "UPDATE_SELECTED_PLAN",
  UPDATE_PICKED_ADD_ONS: "UPDATE_PICKED_ADD_ONS",
};
