import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />

        <title>Frontend Mentor | Space tourism website</title>
      </Head>
      <main style={{ minHeight: '100vh', width: '100%' }}></main>
    </>
  );
}
