import Header from '@/src/components/Header';
import { ReactNode } from 'react';
import Head from 'next/head';
import { styled, useTheme } from '@mui/material';
import { useRouter } from 'next/router';

const Main = styled('main')(() => ({
  minHeight: '100vh',
  backgroundSize: 'cover'
}));

export default function Layout({ children }: { children: ReactNode }) {
  const theme = useTheme();
  const router = useRouter();

  const page = router.asPath === '/' ? 'home' : router.asPath.replace('/', '');

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />

        <title>Space tourism website | {page}</title>
      </Head>
      <Header />
      <Main
        sx={{
          backgroundImage: `url(/${page}/background-${page}-desktop.jpg)`,
          [theme.breakpoints.down('lg')]: {
            backgroundImage: `url(/${page}/background-${page}-tablet.jpg)`
          },
          [theme.breakpoints.down('sm')]: {
            backgroundImage: `url(/${page}/background-${page}-mobile.jpg)`
          }
        }}
      >
        {children}
      </Main>
    </>
  );
}
