import Header from '@/src/components/Header';
import { ReactNode, useEffect, useRef } from 'react';
import Head from 'next/head';
import { Box, styled, useTheme } from '@mui/material';
import { useRouter } from 'next/router';
import PerfectScrollbar from 'react-perfect-scrollbar';

import 'react-perfect-scrollbar/dist/css/styles.css';

const Main = styled('main')(() => ({
  minHeight: '100vh',
  backgroundSize: 'cover'
}));

const scrollStyles = (unit = 4) => ({
  '& .ps__thumb-y': {
    width: unit + 'px'
  },
  '& .ps__thumb-x': {
    height: unit + 'px'
  }
});

export default function Layout({ children }: { children: ReactNode }) {
  const theme = useTheme();
  const router = useRouter();
  const psRef = useRef<PerfectScrollbar | null>(null);
  const divRef = useRef(null);

  const page = router.asPath === '/' ? 'home' : router.asPath.replace('/', '');

  useEffect(() => {
    const observer = new ResizeObserver(entries => {
      const ps = psRef.current;
      if (ps) {
        ps.updateScroll();
      }
    });

    if (divRef.current) {
      observer.observe(divRef.current);
    }

    return () => {
      if (divRef.current) {
        observer.unobserve(divRef.current);
      }
    };
  }, []);

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />

        <title>Space tourism website | {page}</title>
      </Head>
      <Header />
      <Box
        component={PerfectScrollbar}
        sx={{
          height: '100vh',
          '& .ps--clicking': scrollStyles(6),
          ...scrollStyles(),
          '& .ps__rail-y, & .ps__rail-x': {
            '&:hover': scrollStyles(6),
            background: 'transparent !important',
            zIndex: theme => theme.zIndex.appBar * 2
          }
        }}
        ref={psRef}
      >
        <Main
          ref={divRef}
          sx={{
            backgroundImage: `url(/${page}/background-${page}-desktop.jpg)`,
            [theme.breakpoints.down('lg')]: {
              backgroundImage: `url(/${page}/background-${page}-tablet.jpg)`
            },
            [theme.breakpoints.down('sm')]: {
              backgroundImage: `url(/${page}/background-${page}-mobile.jpg)`
            }
          }}
        >
          {children}
        </Main>
      </Box>
    </>
  );
}
