import './globals.css';
import type { Metadata } from 'next';
import ThemeRegistry from '../components/ThemeRegistry';
import { ReactNode } from 'react';
import Header from '@/src/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <ThemeRegistry>
          <Header />
          <main>{children}</main>
        </ThemeRegistry>
      </body>
    </html>
  );
}
